export const DOG_BREEDS = [
  'Australian Shepherd',
  'Beagle',
  'Border Collie',
  'Boxer',
  'Bulldog',
  'Chihuahua',
  'Cocker Spaniel',
  'Dachshund',
  'Doberman',
  'French Bulldog',
  'German Shepherd',
  'Golden Retriever',
  'Great Dane',
  'Husky',
  'Jack Russell Terrier',
  'Labrador Retriever',
  'Maltese',
  'Maltipoo',
  'Pitbull',
  'Poodle',
  'Pomeranian',
  'Rottweiler',
  'Schnauzer',
  'Shih Tzu',
  'Weimaraner',
  'Yorkshire Terrier',
  'Mixed / Rescue',
  'Other',
] as const;

export type DogBreed = (typeof DOG_BREEDS)[number];

export interface BreedFact { fact: string; }

export const BREED_FACTS: Partial<Record<DogBreed, BreedFact[]>> = {
  'Australian Shepherd': [
    { fact: 'A pesar de su nombre, fue desarrollado en Estados Unidos, no en Australia.' },
    { fact: 'Son uno de los perros más inteligentes del mundo. Necesitan ejercicio mental constante o se aburren.' },
    { fact: 'Su pelaje merle (manchado) los hace inconfundibles. No hay dos iguales.' },
    { fact: 'Pueden tener ojos de diferentes colores (heterocromía) — uno azul y uno marrón es común.' },
    { fact: 'Necesitan al menos 1-2 horas de ejercicio diario. No son perros para personas sedentarias.' },
  ],
  'Golden Retriever': [
    { fact: 'Son nadadores natos. Aman el agua.' },
    { fact: 'Son el 4° perro más inteligente del mundo.' },
    { fact: 'Pueden llevar un huevo en la boca sin romperlo gracias a su mordida suave.' },
    { fact: 'Son la raza más usada en películas y comerciales de TV.' },
    { fact: 'Son una de las razas preferidas como perros de terapia y asistencia emocional.' },
  ],
  'Labrador Retriever': [
    { fact: 'La raza más popular del mundo por más de 30 años consecutivos.' },
    { fact: 'Su olfato es 100.000 veces más potente que el humano.' },
    { fact: 'Su pelaje tiene una capa impermeable que repele el agua.' },
    { fact: 'Originarios de Terranova, Canadá. No de Labrador como su nombre sugiere.' },
    { fact: 'Son conocidos por comer sin parar. Tienen una mutación genética que reduce la sensación de saciedad.' },
  ],
  'German Shepherd': [
    { fact: 'La raza más usada por policías y militares del mundo.' },
    { fact: 'Aprenden nuevas órdenes en menos de 5 repeticiones.' },
    { fact: 'Pueden correr hasta 48 km/h.' },
    { fact: 'Un Pastor Alemán llamado Rin Tin Tin fue una estrella de Hollywood en los años 20.' },
    { fact: 'Sus cachorros nacen con orejas caídas. Se levantan entre las 8 y 20 semanas.' },
  ],
  'French Bulldog': [
    { fact: 'No pueden volar solos. Sus narinas cortas dificultan la respiración en alturas.' },
    { fact: 'La mayoría no sabe nadar por su cuerpo robusto y cabeza pesada.' },
    { fact: 'Su oreja en forma de murciélago es su rasgo más distintivo.' },
    { fact: 'Roncan fuerte al dormir por su hocico achatado. Como un humano.' },
    { fact: 'A pesar de su nombre, fueron criados originalmente en Inglaterra, no en Francia.' },
  ],
  'Bulldog': [
    { fact: 'Duermen hasta 12-14 horas al día.' },
    { fact: 'Son el símbolo nacional del Reino Unido.' },
    { fact: 'Odian el calor. Son muy sensibles a las altas temperaturas.' },
    { fact: 'Algunos Bulldogs son famosos por andar en skateboard. Hay videos virales.' },
    { fact: 'Son excelentes con niños pequeños por su temperamento calmado y paciente.' },
  ],
  'Beagle': [
    { fact: 'Tienen 220 millones de receptores olfativos (los humanos tenemos 5 millones).' },
    { fact: 'En vez de ladrar, "aúllan" con un sonido musical característico.' },
    { fact: 'Son el perro más usado en aeropuertos para detectar contrabando.' },
    { fact: 'Snoopy, el perro más famoso de los cómics, es un Beagle.' },
    { fact: 'Son perros de manada. No les gusta estar solos y prefieren compañía.' },
  ],
  'Poodle': [
    { fact: 'Son el 2° perro más inteligente del mundo, detrás del Border Collie.' },
    { fact: 'Originalmente eran perros de caza acuática, no de circo.' },
    { fact: 'Su pelo no se cae — sigue creciendo como el cabello humano.' },
    { fact: 'Aunque se asocian con Francia, su origen es alemán: "Pudel" significa chapotear.' },
    { fact: 'Vienen en 3 tamaños oficiales: estándar, miniatura y toy.' },
  ],
  'Rottweiler': [
    { fact: 'Tienen una de las mordidas más fuertes del reino animal (148 kg de presión).' },
    { fact: 'Eran usados para guiar ganado en la Alemania antigua.' },
    { fact: 'Son perros extremadamente leales y apegados a su familia.' },
    { fact: 'Descienden de los perros pastores del ejército romano.' },
    { fact: 'A pesar de su apariencia intimidante, muchos son verdaderos "bebés gigantes" en casa.' },
  ],
  'Yorkshire Terrier': [
    { fact: 'A pesar de su tamaño, creen que son perros grandes y no temen a nada.' },
    { fact: 'Su pelo es más parecido al cabello humano que a pelaje canino normal.' },
    { fact: 'Originalmente eran cazadores de ratas en las fábricas textiles de Yorkshire.' },
    { fact: 'En la época victoriana se convirtieron en los favoritos de la aristocracia inglesa.' },
    { fact: 'Son una de las razas más pequeñas del mundo. Pesan entre 1.8 y 3.2 kg.' },
  ],
  'Dachshund': [
    { fact: 'Su nombre en alemán significa "perro tejón". Fueron criados para cazar tejones.' },
    { fact: 'En Alemania tienen carreras de Dachshunds que son un evento popular.' },
    { fact: 'Su columna extra larga los hace propensos a problemas de espalda.' },
    { fact: 'Pablo Picasso tenía un Dachshund llamado Lump que aparece en varias de sus obras.' },
    { fact: 'Sus patas cortas y cuerpo largo están diseñados para meterse en madrigueras.' },
  ],
  'Husky': [
    { fact: 'Pueden sobrevivir temperaturas de -60°C gracias a su doble capa de pelo.' },
    { fact: 'Son famosos por "hablar". Emiten sonidos parecidos al habla humana.' },
    { fact: 'Pueden tener ojos de diferentes colores (heterocromía) naturalmente.' },
    { fact: 'En 1925, un equipo de Huskies recorrió 1.085 km para llevar suero antidiftérico a Nome, Alaska.' },
    { fact: 'Mudan TODO su pelo dos veces al año. Prepárate para aspirar mucho.' },
  ],
  'Border Collie': [
    { fact: 'Son el perro más inteligente del mundo. Aprenden comandos en 1-2 repeticiones.' },
    { fact: 'Su "mirada fija" puede controlar rebaños de cientos de ovejas.' },
    { fact: 'Necesitan hasta 2 horas de ejercicio diario para estar equilibrados.' },
    { fact: 'Un Border Collie llamado Chaser aprendió más de 1.000 palabras.' },
    { fact: 'Fueron criados en la frontera (border) entre Escocia e Inglaterra.' },
  ],
  'Jack Russell Terrier': [
    { fact: 'Tienen tanta energía que necesitan más de 1 hora de ejercicio diario.' },
    { fact: 'Fueron criados para cazar zorros metiéndose en sus madrigueras.' },
    { fact: 'Aprenden trucos rapidísimo, pero también se aburren igual de rápido.' },
    { fact: 'Eddie, el Jack Russell de la serie "Frasier", ganaba más que algunos actores del show.' },
    { fact: 'Pueden saltar hasta 1.5 metros de altura: 5 veces su estatura.' },
  ],
  'Boxer': [
    { fact: 'Se llaman Boxer porque "boxean" con sus patas delanteras cuando juegan.' },
    { fact: 'Son excelentes niñeras. Extremadamente pacientes y protectores con niños.' },
    { fact: 'Son conocidos como los "payasos" del mundo canino por sus expresiones cómicas.' },
    { fact: 'Pueden correr hasta 45 km/h y tienen una energía inagotable.' },
    { fact: 'Son propensos a problemas cardíacos. Los chequeos regulares son clave.' },
  ],
  'Chihuahua': [
    { fact: 'Llevan el nombre del estado de Chihuahua en México, donde fueron descubiertos.' },
    { fact: 'Tienen el cerebro más grande en proporción al cuerpo de todas las razas.' },
    { fact: 'Tiemblan mucho. No siempre de frío, también de emoción o energía acumulada.' },
    { fact: 'Los aztecas los consideraban sagrados y guías espirituales.' },
    { fact: 'Viven entre 14 y 18 años. Una de las razas más longevas.' },
  ],
  'Cocker Spaniel': [
    { fact: 'Sus orejas largas ayudan a atrapar olores y dirigirlos hacia su nariz.' },
    { fact: 'La Dama del clásico de Disney "La Dama y el Vagabundo" es una Cocker Spaniel.' },
    { fact: 'Originalmente criados para cazar aves "woodcock". De ahí su nombre.' },
    { fact: 'Son una de las razas más cariñosas. Siempre quieren estar cerca de su dueño.' },
    { fact: 'Sus orejas caídas requieren limpieza frecuente para evitar infecciones.' },
  ],
  'Doberman': [
    { fact: 'Fueron creados por Karl Friedrich Louis Dobermann, un cobrador de impuestos que necesitaba protección.' },
    { fact: 'Son el 5° perro más inteligente del mundo.' },
    { fact: 'Pueden alcanzar velocidades de hasta 40 km/h.' },
    { fact: 'Sirvieron como perros de guerra en ambas Guerras Mundiales.' },
    { fact: 'A pesar de su reputación, son perros extremadamente sensibles y afectuosos en familia.' },
  ],
  'Great Dane': [
    { fact: 'Pueden medir más de 1 metro de altura. El récord fue 1.12m (Zeus, 2011).' },
    { fact: 'A pesar de llamarse "Gran Danés", son originarios de Alemania.' },
    { fact: 'Scooby-Doo es un Gran Danés. El perro más famoso de la TV.' },
    { fact: 'A pesar de su tamaño, son perros tranquilos y les encanta el sofá.' },
    { fact: 'Lamentablemente viven solo 7-10 años. Son "gigantes gentiles" de vida corta.' },
  ],
  'Maltese': [
    { fact: 'Fueron las mascotas favoritas de la realeza durante siglos.' },
    { fact: 'Tienen más de 2.000 años de historia. Aparecen en arte griego y romano.' },
    { fact: 'Son hipoalergénicos. Ideales para personas con alergias al pelo de perro.' },
    { fact: 'Su nombre viene de la isla de Malta en el Mediterráneo.' },
    { fact: 'Su pelo siempre es blanco puro. Es su marca registrada.' },
  ],
  'Pitbull': [
    { fact: 'Antes eran conocidos como "perros niñera" por su paciencia con los niños.' },
    { fact: 'Tienen una fuerza mandibular impresionante, pero no tienen mandíbula "de bloqueo". Es un mito.' },
    { fact: 'Su cara expresiva los hace excelentes en comunicar emociones.' },
    { fact: 'Sergeant Stubby, un Pitbull, fue el perro más condecorado de la Primera Guerra Mundial.' },
    { fact: 'Los Pitbulls puntúan mejor que muchas razas en tests de temperamento.' },
  ],
  'Pomeranian': [
    { fact: 'Parecen pequeños zorros, pero descienden de grandes perros de trineo del Ártico.' },
    { fact: 'La reina Victoria de Inglaterra popularizó la raza — tenía más de 35.' },
    { fact: 'Son grandes ladradores. Excelentes perros alarma a pesar de su tamaño.' },
    { fact: 'Dos Pomeranianos sobrevivieron al hundimiento del Titanic.' },
    { fact: 'Su pelaje doble y esponjoso necesita cepillado varias veces por semana.' },
  ],
  'Schnauzer': [
    { fact: 'Su nombre viene del alemán "Schnauze" (hocico). Por su bigote característico.' },
    { fact: 'Fueron criados originalmente como cazadores de ratas en granjas alemanas.' },
    { fact: 'Son muy inteligentes y fáciles de entrenar, pero también tercos.' },
    { fact: 'No sueltan casi pelo. Son una excelente opción para personas alérgicas.' },
    { fact: 'Tienen unas cejas expresivas que les dan un aspecto de "sabio anciano".' },
  ],
  'Shih Tzu': [
    { fact: 'Su nombre significa "perro león" en chino. Fueron criados para parecerse a leones.' },
    { fact: 'Eran exclusivos de la realeza china. Los plebeyos no podían tener uno.' },
    { fact: 'Les encanta dormir. Pueden pasar hasta 14 horas al día descansando.' },
    { fact: 'Su nariz achatada los hace sensibles al calor. Prefieren ambientes frescos.' },
    { fact: 'Fueron criados específicamente para ser compañeros. Su misión es dar y recibir amor.' },
  ],
  'Weimaraner': [
    { fact: 'Se les llama "fantasmas grises" por su pelaje plateado único.' },
    { fact: 'Necesitan más de 2 horas de ejercicio diario. Son atletas natos.' },
    { fact: 'Fueron criados exclusivamente para la nobleza alemana. Eran "perros de la corte".' },
    { fact: 'El fotógrafo William Wegman los hizo famosos con sus retratos artísticos.' },
    { fact: 'Sufren mucho de ansiedad por separación. No les gusta estar solos.' },
  ],
  'Mixed / Rescue': [
    { fact: 'Los perros mestizos suelen tener menos problemas genéticos que los de raza pura.' },
    { fact: 'Al adoptarlo, salvaste una vida y ganaste un amigo para siempre.' },
    { fact: 'Su mezcla de razas los hace únicos. No hay dos iguales en el mundo.' },
    { fact: 'El vigor híbrido les da una salud más robusta en promedio.' },
    { fact: 'Cada mestizo es una sorpresa. Su personalidad combina lo mejor de varias razas.' },
  ],
  'Other': [
    { fact: 'Hay más de 340 razas de perros reconocidas oficialmente en el mundo.' },
    { fact: 'El olfato de un perro es entre 10.000 y 100.000 veces más potente que el humano.' },
    { fact: 'Los perros pueden entender hasta 250 palabras y gestos diferentes.' },
    { fact: 'Acariciar a un perro reduce la presión arterial y el estrés en humanos.' },
    { fact: 'La temperatura normal de un perro es 38-39°C. Más alta que la humana.' },
  ],
};

// Datos curiosos para gatos — los gatos no manejan razas en Vivra, así que
// es una sola lista general. Usar cuando pet.species === 'cat'.
export const CAT_FACTS: BreedFact[] = [
  { fact: 'Los gatos duermen entre 12 y 16 horas al día — dos tercios de su vida.' },
  { fact: 'El ronroneo vibra entre 25 y 150 Hz, frecuencias asociadas a la regeneración de huesos y tejidos.' },
  { fact: 'La nariz de cada gato tiene un patrón único, como las huellas dactilares humanas.' },
  { fact: 'Los gatos no perciben el sabor dulce — les falta el receptor genético.' },
  { fact: 'Un gato puede saltar hasta 6 veces la longitud de su cuerpo.' },
  { fact: 'Sus bigotes son tan anchos como su cuerpo: los usan para medir si caben por un espacio.' },
  { fact: 'Los gatos adultos casi solo maúllan a los humanos — entre ellos usan otros sonidos y lenguaje corporal.' },
  { fact: 'Pasan hasta la mitad de sus horas despiertos acicalándose.' },
  { fact: 'Pueden girar sus orejas 180 grados gracias a más de 30 músculos en cada una.' },
  { fact: 'La visión nocturna de un gato necesita 6 veces menos luz que la humana.' },
];
