/**
 * Vivra Breed Database
 * Fuentes: AKC breed standards, WSAVA guidelines, VetCompass UK (Pegram 2021),
 * Gough/Thomas/O'Neill "Breed Predispositions to Disease in Dogs and Cats" (3rd ed.),
 * OFA breed statistics, Pet Obesity Prevention ideal weight ranges.
 *
 * Ver: docs/vitality-score-research.md para referencias completas.
 */

export type SizeCategory = 'toy' | 'small' | 'medium' | 'large' | 'giant';
export type RiskLevel = 'low' | 'medium' | 'high' | 'very_high';

export type HealthRisk =
  | 'hip_dysplasia'
  | 'elbow_dysplasia'
  | 'cardiac_disease'
  | 'degenerative_myelopathy'
  | 'brachycephalic_syndrome'
  | 'dental_disease'
  | 'epilepsy'
  | 'cancer'
  | 'obesity'
  | 'eye_disease'
  | 'ear_disease'
  | 'skin_disease'
  | 'bloat'
  | 'patellar_luxation'
  | 'hypothyroidism'
  | 'tracheal_collapse'
  | 'exercise_induced_collapse'
  | 'progressive_retinal_atrophy'
  | 'intervertebral_disc_disease'
  | 'von_willebrand_disease'
  | 'addisons_disease'
  | 'cushings_disease'
  | 'luxating_patella'
  | 'laryngeal_paralysis'
  | 'portosystemic_shunt'
  | 'legg_calve_perthes'
  | 'syringomyelia'
  | 'collie_eye_anomaly'
  | 'pancreatitis'
  | 'deafness'
  | 'urate_stones'
  | 'shar_pei_fever'
  | 'kidney_disease'
  | 'thyroid_disease'
  | 'diabetes'
  | 'protein_losing_nephropathy';

export interface BreedProfile {
  /** Nombre para mostrar */
  displayName: string;
  /** Peso ideal mínimo en kg (macho adulto estándar) */
  idealWeightKgMin: number;
  /** Peso ideal máximo en kg (hembra adulta estándar) */
  idealWeightKgMax: number;
  /** Categoría de tamaño */
  sizeCategory: SizeCategory;
  /** Esperanza de vida promedio en años */
  lifespanYears: number;
  /** Condiciones de salud para las que la raza tiene predisposición documentada */
  risks: HealthRisk[];
  /** Riesgo dental relativo a la población general */
  dentalRisk: RiskLevel;
  /** Riesgo cardíaco relativo */
  cardiacRisk: RiskLevel;
  /** Riesgo de obesidad relativo — basado en VetCompass/Pegram 2021 */
  obesityRisk: RiskLevel;
  /** Edad en años a partir de la cual se considera "senior" */
  seniorAgeYears: number;
}

/**
 * Mapa de razas. Las claves corresponden a los valores del campo `breed` en Supabase.
 * Formato: snake_case del nombre en inglés.
 */
export const BREED_DATA: Record<string, BreedProfile> = {
  labrador_retriever: {
    displayName: 'Labrador Retriever',
    idealWeightKgMin: 25,
    idealWeightKgMax: 36,
    sizeCategory: 'large',
    lifespanYears: 12,
    risks: ['obesity', 'hip_dysplasia', 'elbow_dysplasia', 'exercise_induced_collapse'],
    dentalRisk: 'low',
    cardiacRisk: 'low',
    obesityRisk: 'very_high',
    seniorAgeYears: 7,
  },
  golden_retriever: {
    displayName: 'Golden Retriever',
    idealWeightKgMin: 25,
    idealWeightKgMax: 34,
    sizeCategory: 'large',
    lifespanYears: 11,
    risks: ['cancer', 'hip_dysplasia', 'elbow_dysplasia', 'cardiac_disease'],
    dentalRisk: 'low',
    cardiacRisk: 'medium',
    obesityRisk: 'high',
    seniorAgeYears: 8,
  },
  german_shepherd: {
    displayName: 'Pastor Alemán',
    idealWeightKgMin: 22,
    idealWeightKgMax: 40,
    sizeCategory: 'large',
    lifespanYears: 11,
    risks: ['hip_dysplasia', 'elbow_dysplasia', 'degenerative_myelopathy', 'bloat'],
    dentalRisk: 'low',
    cardiacRisk: 'low',
    obesityRisk: 'medium',
    seniorAgeYears: 7,
  },
  french_bulldog: {
    displayName: 'Bulldog Francés',
    idealWeightKgMin: 8,
    idealWeightKgMax: 13,
    sizeCategory: 'small',
    lifespanYears: 10,
    risks: ['brachycephalic_syndrome', 'intervertebral_disc_disease', 'skin_disease', 'eye_disease'],
    dentalRisk: 'very_high',
    cardiacRisk: 'medium',
    obesityRisk: 'high',
    seniorAgeYears: 8,
  },
  bulldog: {
    displayName: 'Bulldog Inglés',
    idealWeightKgMin: 18,
    idealWeightKgMax: 25,
    sizeCategory: 'medium',
    lifespanYears: 8,
    risks: ['brachycephalic_syndrome', 'hip_dysplasia', 'skin_disease', 'cardiac_disease'],
    dentalRisk: 'very_high',
    cardiacRisk: 'high',
    obesityRisk: 'very_high',
    seniorAgeYears: 6,
  },
  poodle_standard: {
    displayName: 'Poodle (Estándar)',
    idealWeightKgMin: 20,
    idealWeightKgMax: 32,
    sizeCategory: 'large',
    lifespanYears: 14,
    risks: ['hip_dysplasia', 'bloat', 'progressive_retinal_atrophy', 'epilepsy'],
    dentalRisk: 'medium',
    cardiacRisk: 'low',
    obesityRisk: 'low',
    seniorAgeYears: 9,
  },
  poodle_miniature: {
    displayName: 'Poodle (Miniatura)',
    idealWeightKgMin: 4.5,
    idealWeightKgMax: 9,
    sizeCategory: 'small',
    lifespanYears: 15,
    risks: ['patellar_luxation', 'progressive_retinal_atrophy', 'epilepsy', 'dental_disease'],
    dentalRisk: 'high',
    cardiacRisk: 'low',
    obesityRisk: 'low',
    seniorAgeYears: 10,
  },
  poodle_toy: {
    displayName: 'Poodle (Toy)',
    idealWeightKgMin: 2,
    idealWeightKgMax: 4.5,
    sizeCategory: 'toy',
    lifespanYears: 15,
    risks: ['patellar_luxation', 'dental_disease', 'tracheal_collapse', 'progressive_retinal_atrophy'],
    dentalRisk: 'very_high',
    cardiacRisk: 'low',
    obesityRisk: 'low',
    seniorAgeYears: 11,
  },
  beagle: {
    displayName: 'Beagle',
    idealWeightKgMin: 9,
    idealWeightKgMax: 14,
    sizeCategory: 'small',
    lifespanYears: 13,
    risks: ['obesity', 'epilepsy', 'hypothyroidism', 'eye_disease'],
    dentalRisk: 'medium',
    cardiacRisk: 'low',
    obesityRisk: 'very_high',
    seniorAgeYears: 9,
  },
  rottweiler: {
    displayName: 'Rottweiler',
    idealWeightKgMin: 35,
    idealWeightKgMax: 60,
    sizeCategory: 'large',
    lifespanYears: 9,
    risks: ['hip_dysplasia', 'elbow_dysplasia', 'cancer', 'cardiac_disease'],
    dentalRisk: 'low',
    cardiacRisk: 'medium',
    obesityRisk: 'medium',
    seniorAgeYears: 7,
  },
  dachshund: {
    displayName: 'Dachshund (Salchicha)',
    idealWeightKgMin: 3,
    idealWeightKgMax: 9,
    sizeCategory: 'small',
    lifespanYears: 14,
    risks: ['intervertebral_disc_disease', 'dental_disease', 'obesity', 'progressive_retinal_atrophy'],
    dentalRisk: 'high',
    cardiacRisk: 'low',
    obesityRisk: 'high',
    seniorAgeYears: 10,
  },
  yorkshire_terrier: {
    displayName: 'Yorkshire Terrier',
    idealWeightKgMin: 1.8,
    idealWeightKgMax: 3.2,
    sizeCategory: 'toy',
    lifespanYears: 15,
    risks: ['dental_disease', 'tracheal_collapse', 'patellar_luxation', 'portosystemic_shunt'],
    dentalRisk: 'very_high',
    cardiacRisk: 'low',
    obesityRisk: 'low',
    seniorAgeYears: 11,
  },
  boxer: {
    displayName: 'Boxer',
    idealWeightKgMin: 22,
    idealWeightKgMax: 32,
    sizeCategory: 'large',
    lifespanYears: 10,
    risks: ['cardiac_disease', 'cancer', 'brachycephalic_syndrome', 'hip_dysplasia'],
    dentalRisk: 'medium',
    cardiacRisk: 'very_high',
    obesityRisk: 'medium',
    seniorAgeYears: 7,
  },
  siberian_husky: {
    displayName: 'Siberian Husky',
    idealWeightKgMin: 16,
    idealWeightKgMax: 27,
    sizeCategory: 'medium',
    lifespanYears: 13,
    risks: ['eye_disease', 'hip_dysplasia', 'hypothyroidism', 'skin_disease'],
    dentalRisk: 'low',
    cardiacRisk: 'low',
    obesityRisk: 'low',
    seniorAgeYears: 9,
  },
  great_dane: {
    displayName: 'Gran Danés',
    idealWeightKgMin: 45,
    idealWeightKgMax: 90,
    sizeCategory: 'giant',
    lifespanYears: 8,
    risks: ['bloat', 'cardiac_disease', 'hip_dysplasia', 'cancer'],
    dentalRisk: 'low',
    cardiacRisk: 'high',
    obesityRisk: 'medium',
    seniorAgeYears: 5,
  },
  chihuahua: {
    displayName: 'Chihuahua',
    idealWeightKgMin: 1.5,
    idealWeightKgMax: 3,
    sizeCategory: 'toy',
    lifespanYears: 16,
    risks: ['dental_disease', 'patellar_luxation', 'tracheal_collapse', 'cardiac_disease'],
    dentalRisk: 'very_high',
    cardiacRisk: 'medium',
    obesityRisk: 'low',
    seniorAgeYears: 11,
  },
  shih_tzu: {
    displayName: 'Shih Tzu',
    idealWeightKgMin: 4,
    idealWeightKgMax: 7.5,
    sizeCategory: 'small',
    lifespanYears: 14,
    risks: ['brachycephalic_syndrome', 'eye_disease', 'dental_disease', 'intervertebral_disc_disease'],
    dentalRisk: 'very_high',
    cardiacRisk: 'medium',
    obesityRisk: 'medium',
    seniorAgeYears: 10,
  },
  doberman_pinscher: {
    displayName: 'Doberman',
    idealWeightKgMin: 27,
    idealWeightKgMax: 45,
    sizeCategory: 'large',
    lifespanYears: 10,
    risks: ['cardiac_disease', 'von_willebrand_disease', 'bloat', 'hypothyroidism'],
    dentalRisk: 'low',
    cardiacRisk: 'very_high',
    obesityRisk: 'low',
    seniorAgeYears: 7,
  },
  australian_shepherd: {
    displayName: 'Australian Shepherd',
    idealWeightKgMin: 16,
    idealWeightKgMax: 32,
    sizeCategory: 'medium',
    lifespanYears: 13,
    risks: ['hip_dysplasia', 'epilepsy', 'progressive_retinal_atrophy', 'cancer'],
    dentalRisk: 'low',
    cardiacRisk: 'low',
    obesityRisk: 'low',
    seniorAgeYears: 9,
  },
  cavalier_king_charles_spaniel: {
    displayName: 'Cavalier King Charles Spaniel',
    idealWeightKgMin: 5.5,
    idealWeightKgMax: 9,
    sizeCategory: 'small',
    lifespanYears: 12,
    risks: ['cardiac_disease', 'syringomyelia', 'eye_disease', 'obesity'],
    dentalRisk: 'high',
    cardiacRisk: 'very_high',
    obesityRisk: 'very_high',
    seniorAgeYears: 9,
  },
  cocker_spaniel: {
    displayName: 'Cocker Spaniel',
    idealWeightKgMin: 9,
    idealWeightKgMax: 14.5,
    sizeCategory: 'small',
    lifespanYears: 13,
    risks: ['ear_disease', 'obesity', 'eye_disease', 'hypothyroidism'],
    dentalRisk: 'medium',
    cardiacRisk: 'low',
    obesityRisk: 'very_high',
    seniorAgeYears: 9,
  },
  border_collie: {
    displayName: 'Border Collie',
    idealWeightKgMin: 12,
    idealWeightKgMax: 20,
    sizeCategory: 'medium',
    lifespanYears: 14,
    risks: ['epilepsy', 'hip_dysplasia', 'progressive_retinal_atrophy', 'collie_eye_anomaly'],
    dentalRisk: 'low',
    cardiacRisk: 'low',
    obesityRisk: 'low',
    seniorAgeYears: 10,
  },
  maltese: {
    displayName: 'Maltés',
    idealWeightKgMin: 1.4,
    idealWeightKgMax: 3.2,
    sizeCategory: 'toy',
    lifespanYears: 15,
    risks: ['dental_disease', 'patellar_luxation', 'portosystemic_shunt', 'tracheal_collapse'],
    dentalRisk: 'very_high',
    cardiacRisk: 'low',
    obesityRisk: 'low',
    seniorAgeYears: 11,
  },
  pomeranian: {
    displayName: 'Pomerania',
    idealWeightKgMin: 1.4,
    idealWeightKgMax: 3.2,
    sizeCategory: 'toy',
    lifespanYears: 14,
    risks: ['dental_disease', 'tracheal_collapse', 'patellar_luxation', 'cardiac_disease'],
    dentalRisk: 'very_high',
    cardiacRisk: 'medium',
    obesityRisk: 'low',
    seniorAgeYears: 10,
  },
  schnauzer_miniature: {
    displayName: 'Schnauzer Miniatura',
    idealWeightKgMin: 4.5,
    idealWeightKgMax: 9,
    sizeCategory: 'small',
    lifespanYears: 14,
    risks: ['dental_disease', 'pancreatitis', 'eye_disease', 'hypothyroidism'],
    dentalRisk: 'high',
    cardiacRisk: 'low',
    obesityRisk: 'medium',
    seniorAgeYears: 10,
  },
  schnauzer_standard: {
    displayName: 'Schnauzer Estándar',
    idealWeightKgMin: 14,
    idealWeightKgMax: 20,
    sizeCategory: 'medium',
    lifespanYears: 14,
    risks: ['hip_dysplasia', 'eye_disease', 'skin_disease', 'cancer'],
    dentalRisk: 'medium',
    cardiacRisk: 'low',
    obesityRisk: 'low',
    seniorAgeYears: 9,
  },
  schnauzer_giant: {
    displayName: 'Schnauzer Gigante',
    idealWeightKgMin: 25,
    idealWeightKgMax: 48,
    sizeCategory: 'large',
    lifespanYears: 12,
    risks: ['hip_dysplasia', 'cancer', 'bloat', 'hypothyroidism'],
    dentalRisk: 'low',
    cardiacRisk: 'low',
    obesityRisk: 'low',
    seniorAgeYears: 8,
  },
  weimaraner: {
    displayName: 'Weimaraner',
    idealWeightKgMin: 23,
    idealWeightKgMax: 36,
    sizeCategory: 'large',
    lifespanYears: 12,
    risks: ['bloat', 'hip_dysplasia', 'cancer', 'hypothyroidism'],
    dentalRisk: 'low',
    cardiacRisk: 'low',
    obesityRisk: 'low',
    seniorAgeYears: 8,
  },
  dalmatian: {
    displayName: 'Dálmata',
    idealWeightKgMin: 16,
    idealWeightKgMax: 32,
    sizeCategory: 'medium',
    lifespanYears: 13,
    risks: ['deafness', 'urate_stones', 'hip_dysplasia', 'eye_disease'],
    dentalRisk: 'low',
    cardiacRisk: 'low',
    obesityRisk: 'low',
    seniorAgeYears: 9,
  },
  shar_pei: {
    displayName: 'Shar Pei',
    idealWeightKgMin: 18,
    idealWeightKgMax: 25,
    sizeCategory: 'medium',
    lifespanYears: 11,
    risks: ['skin_disease', 'eye_disease', 'hip_dysplasia', 'shar_pei_fever'],
    dentalRisk: 'medium',
    cardiacRisk: 'low',
    obesityRisk: 'medium',
    seniorAgeYears: 8,
  },
  basset_hound: {
    displayName: 'Basset Hound',
    idealWeightKgMin: 18,
    idealWeightKgMax: 27,
    sizeCategory: 'medium',
    lifespanYears: 12,
    risks: ['obesity', 'intervertebral_disc_disease', 'ear_disease', 'eye_disease'],
    dentalRisk: 'medium',
    cardiacRisk: 'low',
    obesityRisk: 'very_high',
    seniorAgeYears: 8,
  },
  bernese_mountain_dog: {
    displayName: 'Boyero de Berna',
    idealWeightKgMin: 32,
    idealWeightKgMax: 52,
    sizeCategory: 'large',
    lifespanYears: 8,
    risks: ['cancer', 'hip_dysplasia', 'elbow_dysplasia', 'cardiac_disease'],
    dentalRisk: 'low',
    cardiacRisk: 'medium',
    obesityRisk: 'medium',
    seniorAgeYears: 6,
  },
  bichon_frise: {
    displayName: 'Bichón Frisé',
    idealWeightKgMin: 3,
    idealWeightKgMax: 5.5,
    sizeCategory: 'small',
    lifespanYears: 14,
    risks: ['dental_disease', 'patellar_luxation', 'skin_disease', 'eye_disease'],
    dentalRisk: 'very_high',
    cardiacRisk: 'low',
    obesityRisk: 'low',
    seniorAgeYears: 10,
  },
  boston_terrier: {
    displayName: 'Boston Terrier',
    idealWeightKgMin: 4.5,
    idealWeightKgMax: 11,
    sizeCategory: 'small',
    lifespanYears: 13,
    risks: ['brachycephalic_syndrome', 'eye_disease', 'patellar_luxation', 'dental_disease'],
    dentalRisk: 'very_high',
    cardiacRisk: 'medium',
    obesityRisk: 'medium',
    seniorAgeYears: 9,
  },
  chow_chow: {
    displayName: 'Chow Chow',
    idealWeightKgMin: 20,
    idealWeightKgMax: 32,
    sizeCategory: 'medium',
    lifespanYears: 11,
    risks: ['hip_dysplasia', 'skin_disease', 'eye_disease', 'hypothyroidism'],
    dentalRisk: 'medium',
    cardiacRisk: 'low',
    obesityRisk: 'high',
    seniorAgeYears: 8,
  },
  collie: {
    displayName: 'Collie',
    idealWeightKgMin: 18,
    idealWeightKgMax: 34,
    sizeCategory: 'medium',
    lifespanYears: 13,
    risks: ['collie_eye_anomaly', 'progressive_retinal_atrophy', 'hip_dysplasia', 'epilepsy'],
    dentalRisk: 'low',
    cardiacRisk: 'low',
    obesityRisk: 'low',
    seniorAgeYears: 9,
  },
  corgi_pembroke: {
    displayName: 'Corgi Pembroke',
    idealWeightKgMin: 11,
    idealWeightKgMax: 14,
    sizeCategory: 'small',
    lifespanYears: 13,
    risks: ['intervertebral_disc_disease', 'obesity', 'hip_dysplasia', 'progressive_retinal_atrophy'],
    dentalRisk: 'medium',
    cardiacRisk: 'low',
    obesityRisk: 'high',
    seniorAgeYears: 9,
  },
  corgi_cardigan: {
    displayName: 'Corgi Cardigan',
    idealWeightKgMin: 11,
    idealWeightKgMax: 17,
    sizeCategory: 'small',
    lifespanYears: 13,
    risks: ['intervertebral_disc_disease', 'obesity', 'hip_dysplasia', 'eye_disease'],
    dentalRisk: 'medium',
    cardiacRisk: 'low',
    obesityRisk: 'high',
    seniorAgeYears: 9,
  },
  english_springer_spaniel: {
    displayName: 'English Springer Spaniel',
    idealWeightKgMin: 18,
    idealWeightKgMax: 25,
    sizeCategory: 'medium',
    lifespanYears: 13,
    risks: ['hip_dysplasia', 'ear_disease', 'obesity', 'eye_disease'],
    dentalRisk: 'medium',
    cardiacRisk: 'low',
    obesityRisk: 'high',
    seniorAgeYears: 9,
  },
  german_shorthaired_pointer: {
    displayName: 'Braco Alemán',
    idealWeightKgMin: 20,
    idealWeightKgMax: 32,
    sizeCategory: 'large',
    lifespanYears: 13,
    risks: ['hip_dysplasia', 'bloat', 'cancer', 'cardiac_disease'],
    dentalRisk: 'low',
    cardiacRisk: 'medium',
    obesityRisk: 'low',
    seniorAgeYears: 9,
  },
  greyhound: {
    displayName: 'Galgo (Greyhound)',
    idealWeightKgMin: 25,
    idealWeightKgMax: 40,
    sizeCategory: 'large',
    lifespanYears: 13,
    risks: ['cardiac_disease', 'bloat', 'skin_disease', 'cancer'],
    dentalRisk: 'medium',
    cardiacRisk: 'medium',
    obesityRisk: 'low',
    seniorAgeYears: 9,
  },
  jack_russell_terrier: {
    displayName: 'Jack Russell Terrier',
    idealWeightKgMin: 5,
    idealWeightKgMax: 8,
    sizeCategory: 'small',
    lifespanYears: 15,
    risks: ['patellar_luxation', 'eye_disease', 'deafness', 'legg_calve_perthes'],
    dentalRisk: 'medium',
    cardiacRisk: 'low',
    obesityRisk: 'low',
    seniorAgeYears: 10,
  },
  lhasa_apso: {
    displayName: 'Lhasa Apso',
    idealWeightKgMin: 5,
    idealWeightKgMax: 8,
    sizeCategory: 'small',
    lifespanYears: 15,
    risks: ['kidney_disease', 'eye_disease', 'intervertebral_disc_disease', 'dental_disease'],
    dentalRisk: 'very_high',
    cardiacRisk: 'low',
    obesityRisk: 'low',
    seniorAgeYears: 10,
  },
  mastiff: {
    displayName: 'Mastín',
    idealWeightKgMin: 54,
    idealWeightKgMax: 100,
    sizeCategory: 'giant',
    lifespanYears: 8,
    risks: ['hip_dysplasia', 'elbow_dysplasia', 'bloat', 'cancer'],
    dentalRisk: 'low',
    cardiacRisk: 'medium',
    obesityRisk: 'medium',
    seniorAgeYears: 5,
  },
  newfoundland: {
    displayName: 'Terranova',
    idealWeightKgMin: 45,
    idealWeightKgMax: 68,
    sizeCategory: 'giant',
    lifespanYears: 9,
    risks: ['hip_dysplasia', 'cardiac_disease', 'bloat', 'cancer'],
    dentalRisk: 'low',
    cardiacRisk: 'high',
    obesityRisk: 'medium',
    seniorAgeYears: 6,
  },
  papillon: {
    displayName: 'Papillón',
    idealWeightKgMin: 2,
    idealWeightKgMax: 5,
    sizeCategory: 'toy',
    lifespanYears: 15,
    risks: ['dental_disease', 'patellar_luxation', 'cardiac_disease', 'progressive_retinal_atrophy'],
    dentalRisk: 'very_high',
    cardiacRisk: 'medium',
    obesityRisk: 'low',
    seniorAgeYears: 10,
  },
  pug: {
    displayName: 'Pug (Carlino)',
    idealWeightKgMin: 6,
    idealWeightKgMax: 9,
    sizeCategory: 'small',
    lifespanYears: 13,
    risks: ['brachycephalic_syndrome', 'obesity', 'eye_disease', 'skin_disease'],
    dentalRisk: 'very_high',
    cardiacRisk: 'medium',
    obesityRisk: 'very_high',
    seniorAgeYears: 9,
  },
  rhodesian_ridgeback: {
    displayName: 'Rhodesian Ridgeback',
    idealWeightKgMin: 29,
    idealWeightKgMax: 41,
    sizeCategory: 'large',
    lifespanYears: 12,
    risks: ['hip_dysplasia', 'elbow_dysplasia', 'bloat', 'thyroid_disease'],
    dentalRisk: 'low',
    cardiacRisk: 'low',
    obesityRisk: 'low',
    seniorAgeYears: 8,
  },
  saint_bernard: {
    displayName: 'San Bernardo',
    idealWeightKgMin: 54,
    idealWeightKgMax: 90,
    sizeCategory: 'giant',
    lifespanYears: 8,
    risks: ['hip_dysplasia', 'elbow_dysplasia', 'bloat', 'cardiac_disease'],
    dentalRisk: 'low',
    cardiacRisk: 'medium',
    obesityRisk: 'medium',
    seniorAgeYears: 5,
  },
  samoyed: {
    displayName: 'Samoyedo',
    idealWeightKgMin: 16,
    idealWeightKgMax: 30,
    sizeCategory: 'medium',
    lifespanYears: 13,
    risks: ['hip_dysplasia', 'cardiac_disease', 'eye_disease', 'diabetes'],
    dentalRisk: 'low',
    cardiacRisk: 'medium',
    obesityRisk: 'low',
    seniorAgeYears: 9,
  },
  scottish_terrier: {
    displayName: 'Scottish Terrier',
    idealWeightKgMin: 8,
    idealWeightKgMax: 10,
    sizeCategory: 'small',
    lifespanYears: 12,
    risks: ['cancer', 'dental_disease', 'addisons_disease', 'von_willebrand_disease'],
    dentalRisk: 'high',
    cardiacRisk: 'low',
    obesityRisk: 'medium',
    seniorAgeYears: 9,
  },
  soft_coated_wheaten_terrier: {
    displayName: 'Soft Coated Wheaten Terrier',
    idealWeightKgMin: 14,
    idealWeightKgMax: 20,
    sizeCategory: 'medium',
    lifespanYears: 13,
    risks: ['protein_losing_nephropathy', 'addisons_disease', 'hip_dysplasia', 'skin_disease'],
    dentalRisk: 'medium',
    cardiacRisk: 'low',
    obesityRisk: 'low',
    seniorAgeYears: 9,
  },
  staffordshire_bull_terrier: {
    displayName: 'Staffordshire Bull Terrier',
    idealWeightKgMin: 11,
    idealWeightKgMax: 17,
    sizeCategory: 'medium',
    lifespanYears: 13,
    risks: ['skin_disease', 'eye_disease', 'cardiac_disease', 'obesity'],
    dentalRisk: 'medium',
    cardiacRisk: 'medium',
    obesityRisk: 'high',
    seniorAgeYears: 9,
  },
  vizsla: {
    displayName: 'Vizsla',
    idealWeightKgMin: 18,
    idealWeightKgMax: 29,
    sizeCategory: 'medium',
    lifespanYears: 13,
    risks: ['hip_dysplasia', 'epilepsy', 'cardiac_disease', 'cancer'],
    dentalRisk: 'low',
    cardiacRisk: 'medium',
    obesityRisk: 'low',
    seniorAgeYears: 9,
  },
  whippet: {
    displayName: 'Whippet',
    idealWeightKgMin: 9,
    idealWeightKgMax: 19,
    sizeCategory: 'medium',
    lifespanYears: 14,
    risks: ['cardiac_disease', 'eye_disease', 'hypothyroidism', 'skin_disease'],
    dentalRisk: 'medium',
    cardiacRisk: 'medium',
    obesityRisk: 'low',
    seniorAgeYears: 10,
  },
  irish_setter: {
    displayName: 'Irish Setter',
    idealWeightKgMin: 24,
    idealWeightKgMax: 32,
    sizeCategory: 'large',
    lifespanYears: 13,
    risks: ['hip_dysplasia', 'progressive_retinal_atrophy', 'bloat', 'epilepsy'],
    dentalRisk: 'low',
    cardiacRisk: 'low',
    obesityRisk: 'low',
    seniorAgeYears: 9,
  },
  // Fallback para razas no listadas, cruzados, rescatados, callejeros
  mixed: {
    displayName: 'Mestizo / Rescatado',
    idealWeightKgMin: 10,
    idealWeightKgMax: 30,
    sizeCategory: 'medium',
    lifespanYears: 13,
    risks: [],
    dentalRisk: 'medium',
    cardiacRisk: 'low',
    obesityRisk: 'medium',
    seniorAgeYears: 9,
  },
};

/**
 * Normaliza el nombre de raza del usuario a la clave del mapa.
 * Maneja variantes comunes en español e inglés.
 */
export function normalizeBreedKey(breed: string | null | undefined): string {
  if (!breed) return 'mixed';

  const normalized = breed
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '') // quita acentos
    .replace(/[^a-z0-9\s]/g, '')
    .trim();

  // Aliases en español → clave inglesa
  const aliases: Record<string, string> = {
    'labrador': 'labrador_retriever',
    'labrador retriever': 'labrador_retriever',
    'golden': 'golden_retriever',
    'golden retriever': 'golden_retriever',
    'pastor aleman': 'german_shepherd',
    'pastor alemán': 'german_shepherd',
    'german shepherd': 'german_shepherd',
    'bulldog frances': 'french_bulldog',
    'bulldog francés': 'french_bulldog',
    'french bulldog': 'french_bulldog',
    'bulldog ingles': 'bulldog',
    'bulldog inglés': 'bulldog',
    'bulldog': 'bulldog',
    'poodle': 'poodle_standard',
    'caniche': 'poodle_standard',
    'caniche estandar': 'poodle_standard',
    'caniche miniatura': 'poodle_miniature',
    'caniche toy': 'poodle_toy',
    'beagle': 'beagle',
    'rottweiler': 'rottweiler',
    'salchicha': 'dachshund',
    'dachshund': 'dachshund',
    'teckel': 'dachshund',
    'yorkshire': 'yorkshire_terrier',
    'yorkshire terrier': 'yorkshire_terrier',
    'yorkie': 'yorkshire_terrier',
    'boxer': 'boxer',
    'husky': 'siberian_husky',
    'siberian husky': 'siberian_husky',
    'gran danes': 'great_dane',
    'gran danés': 'great_dane',
    'great dane': 'great_dane',
    'chihuahua': 'chihuahua',
    'shih tzu': 'shih_tzu',
    'doberman': 'doberman_pinscher',
    'dobermann': 'doberman_pinscher',
    'australian shepherd': 'australian_shepherd',
    'pastor australiano': 'australian_shepherd',
    'cavalier': 'cavalier_king_charles_spaniel',
    'cavalier king charles': 'cavalier_king_charles_spaniel',
    'cocker': 'cocker_spaniel',
    'cocker spaniel': 'cocker_spaniel',
    'border collie': 'border_collie',
    'maltes': 'maltese',
    'maltés': 'maltese',
    'maltese': 'maltese',
    'pomerania': 'pomeranian',
    'pomeranian': 'pomeranian',
    'spitz': 'pomeranian',
    'schnauzer': 'schnauzer_miniature',
    'schnauzer miniatura': 'schnauzer_miniature',
    'schnauzer estandar': 'schnauzer_standard',
    'schnauzer gigante': 'schnauzer_giant',
    'weimaraner': 'weimaraner',
    'dalmata': 'dalmatian',
    'dálmata': 'dalmatian',
    'dalmatian': 'dalmatian',
    'shar pei': 'shar_pei',
    'basset': 'basset_hound',
    'basset hound': 'basset_hound',
    'bernes': 'bernese_mountain_dog',
    'boyero de berna': 'bernese_mountain_dog',
    'bernese mountain dog': 'bernese_mountain_dog',
    'bichon': 'bichon_frise',
    'bichon frise': 'bichon_frise',
    'bichón frisé': 'bichon_frise',
    'boston terrier': 'boston_terrier',
    'chow chow': 'chow_chow',
    'collie': 'collie',
    'corgi': 'corgi_pembroke',
    'corgi pembroke': 'corgi_pembroke',
    'corgi cardigan': 'corgi_cardigan',
    'springer': 'english_springer_spaniel',
    'english springer': 'english_springer_spaniel',
    'braco aleman': 'german_shorthaired_pointer',
    'braco alemán': 'german_shorthaired_pointer',
    'galgo': 'greyhound',
    'greyhound': 'greyhound',
    'jack russell': 'jack_russell_terrier',
    'jack russell terrier': 'jack_russell_terrier',
    'lhasa': 'lhasa_apso',
    'lhasa apso': 'lhasa_apso',
    'mastin': 'mastiff',
    'mastín': 'mastiff',
    'mastiff': 'mastiff',
    'terranova': 'newfoundland',
    'newfoundland': 'newfoundland',
    'papillon': 'papillon',
    'papillón': 'papillon',
    'pug': 'pug',
    'carlino': 'pug',
    'rhodesian': 'rhodesian_ridgeback',
    'rhodesian ridgeback': 'rhodesian_ridgeback',
    'san bernardo': 'saint_bernard',
    'saint bernard': 'saint_bernard',
    'samoyedo': 'samoyed',
    'samoyed': 'samoyed',
    'scottish terrier': 'scottish_terrier',
    'scotty': 'scottish_terrier',
    'wheaten': 'soft_coated_wheaten_terrier',
    'staffordshire': 'staffordshire_bull_terrier',
    'staffie': 'staffordshire_bull_terrier',
    'pitbull': 'staffordshire_bull_terrier',
    'pit bull': 'staffordshire_bull_terrier',
    'american pit bull': 'staffordshire_bull_terrier',
    'vizsla': 'vizsla',
    'whippet': 'whippet',
    'setter irlandes': 'irish_setter',
    'setter irlandés': 'irish_setter',
    'irish setter': 'irish_setter',
    'mestizo': 'mixed',
    'cruzado': 'mixed',
    'mixto': 'mixed',
    'mixed': 'mixed',
    'mixed rescue': 'mixed',
    'mixed  rescue': 'mixed',
    'desconocido': 'mixed',
    'other': 'mixed',
    'rescue': 'mixed',
    'rescatado': 'mixed',
    'rescatada': 'mixed',
    'adoptado': 'mixed',
    'adoptada': 'mixed',
    'callejero': 'mixed',
    'callejera': 'mixed',
    'criollo': 'mixed',
    'criolla': 'mixed',
    'perro de calle': 'mixed',
    'sin raza': 'mixed',
    'mutt': 'mixed',
    'mongrel': 'mixed',
    'stray': 'mixed',
    'sato': 'mixed',
    'potcake': 'mixed',
    'aspin': 'mixed',
    'indie': 'mixed',
    'perro mestizo': 'mixed',
  };

  // Búsqueda directa
  if (aliases[normalized]) return aliases[normalized];

  // Búsqueda parcial si no hay coincidencia exacta
  for (const [alias, key] of Object.entries(aliases)) {
    if (normalized.includes(alias) || alias.includes(normalized)) return key;
  }

  return 'mixed';
}

/**
 * Retorna el perfil de raza dado el nombre de raza del usuario.
 * Nunca retorna undefined — usa 'mixed' como fallback.
 */
export function getBreedProfile(breed: string | null | undefined): BreedProfile {
  const key = normalizeBreedKey(breed);
  return BREED_DATA[key] ?? BREED_DATA['mixed'];
}

/**
 * Calcula el peso ideal central para una raza (promedio de min y max).
 */
export function getIdealWeight(breed: string | null | undefined): number {
  const profile = getBreedProfile(breed);
  return (profile.idealWeightKgMin + profile.idealWeightKgMax) / 2;
}

/**
 * Calcula si un perro es "senior" dado su raza y edad en años.
 */
export function isSenior(breed: string | null | undefined, ageYears: number): boolean {
  const profile = getBreedProfile(breed);
  return ageYears >= profile.seniorAgeYears;
}
